services:
  db:
    image: postgres:latest
    container_name: sps-postgres
    volumes:
      - ./db/sample/:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: imdb

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: sps-pgadmin
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@example.com
      PGADMIN_DEFAULT_PASSWORD: pgadmin
