services:
  db:
    image: postgres:latest
    container_name: sps-postgres
    volumes:
      - ./db/prod/:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: imdb
